// Code generated by "stringer -type=BaseModifier"; DO NOT EDIT.

package expreval

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BaseModifierNone-0]
	_ = x[BaseModifierBin-1]
	_ = x[BaseModifierOct-2]
	_ = x[BaseModifierHex-3]
}

const _BaseModifier_name = "BaseModifierNoneBaseModifierBinBaseModifierOctBaseModifierHex"

var _BaseModifier_index = [...]uint8{0, 16, 31, 46, 61}

func (i BaseModifier) String() string {
	if i < 0 || i >= BaseModifier(len(_BaseModifier_index)-1) {
		return "BaseModifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseModifier_name[_BaseModifier_index[i]:_BaseModifier_index[i+1]]
}
